// Generated by CoffeeScript 1.8.0
(function() {
  var Match, Neo4jEndpoint, check, _, _ref;

  _ref = require('./check'), check = _ref.check, Match = _ref.Match;

  _ = require('./helpers')._;


  /*
  @locus Server
  @summary Represents Neo4j endpoints
           Usually not used directly, it is used internally.
  @class Neo4jEndpoint
   */

  module.exports = Neo4jEndpoint = (function() {
    function Neo4jEndpoint(key, endpoint, _db) {
      this.key = key;
      this.endpoint = endpoint;
      this._db = _db;
      check(this.key, String);
      check(this.endpoint, String);
    }

    Neo4jEndpoint.prototype.get = function(method, options, directly) {
      var data;
      if (method == null) {
        method = 'GET';
      }
      if (options == null) {
        options = {};
      }
      if (directly) {
        return this._db.__call(this.endpoint, options, method).data;
      } else {
        data = this._db.__batch({
          method: method,
          to: this.endpoint,
          body: (options != null ? options.body : void 0) ? options.body : null
        });
        data = (data != null ? typeof data.get === "function" ? data.get() : void 0 : void 0) || data;
        return data;
      }
    };

    Neo4jEndpoint.prototype.__getAndProceed = function(funcName) {
      return this._db[funcName](this._db.__batch({
        method: 'GET',
        to: this.endpoint
      }, void 0, false, true));
    };

    return Neo4jEndpoint;

  })();

}).call(this);
