// Generated by CoffeeScript 1.8.0
(function() {
  var Fiber, Neo4jDB, _, _ref;

  Neo4jDB = require('./index').Neo4jDB;

  _ref = require('./helpers'), Fiber = _ref.Fiber, _ = _ref._;


  /*
  After running code below it should output `true` - 11 times
  Change credentials below in according with your Neo4j DB
   */

  Fiber(function() {
    var current, db, n1, node, result, t;
    db = new Neo4jDB('http://localhost:7474', {
      username: 'neo4j',
      password: '1234'
    });
    console.log(_.isArray(db.query("MATCH n RETURN n").fetch()));

    /*
    Transaction test
    Want to see more tests and examples? - Contribute!
     */
    t = db.transaction("CREATE (n:TransactionsTesting {data}) RETURN n", {
      data: {
        transaction: true
      }
    });
    current = t.current();
    node = current[0].fetch()[0];
    t.execute("CREATE (n:TransactionsTesting2 {data}) RETURN n", {
      data: {
        transaction2: true
      }
    });
    current = t.current();
    node = current[1].fetch()[0];
    result = t.commit();
    console.log(JSON.stringify(db.queryOne("MATCH (n:TransactionsTesting) RETURN n").n) === JSON.stringify(result[0].fetch()[0].n));
    console.log(JSON.stringify(db.queryOne("MATCH (n:TransactionsTesting2) RETURN n").n) === JSON.stringify(result[1].fetch()[0].n));
    db.transaction().commit("MATCH (n:TransactionsTesting), (n2:TransactionsTesting2) DELETE n, n2");
    console.log(db.queryOne("MATCH (n:TransactionsTesting) RETURN n") === void 0);
    console.log(db.queryOne("MATCH (n:TransactionsTesting2) RETURN n") === void 0);
    console.log(_.isArray(db.propertyKeys()));
    console.log(_.isArray(db.labels()));
    console.log(_.isArray(db.relationshipTypes()));
    console.log(_.isString(db.version()));

    /*
    Create, retrieve and remove a node
     */
    n1 = db.nodes({
      test: true,
      asdasd: 'asjkdhkajs'
    });
    console.log(_.isObject(n1.get()));
    return console.log(_.isUndefined(n1["delete"]()));
  }).run();

}).call(this);
