// Generated by CoffeeScript 1.8.0
(function() {
  var Fiber, Future, colorize, _, __error, __success;

  colorize = function(args, color) {
    var arg, error, messages, _i, _len;
    messages = ['\x1b[1m', "\x1b[" + color + "m"];
    for (_i = 0, _len = args.length; _i < _len; _i++) {
      arg = args[_i];
      try {
        messages.push(_.isObject(arg) ? arg.toString() : arg);
      } catch (_error) {
        error = _error;
        messages.push(JSON.stringify(arg, null, 2));
      }
    }
    messages.push('\x1b[39m', '\x1b[22m\x1b[0m');
    return messages;
  };

  __success = function() {
    return process.stdout.write(colorize(arguments, '32').join('') + '\r\n');
  };

  __error = function() {
    return process.stdout.write(colorize(arguments, '31').join('') + '\r\n');
  };

  Function.prototype.define = function(name, getSet) {
    return Object.defineProperty(this.prototype, name, getSet);
  };

  Fiber = require('fibers');

  Future = require('fibers/future');

  _ = require('underscore');

  module.exports = {
    _: _,
    NTRU_def: process.env.NODE_TLS_REJECT_UNAUTHORIZED,
    bound: function(cb) {
      return Fiber(function() {
        return cb();
      }).run();
    },
    __success: __success,
    __error: __error,
    events: require('events'),
    URL: require('url'),
    needle: require('needle'),
    Future: Future,
    Fiber: Fiber,
    __wait: function(cb) {
      var fut;
      fut = new Future();
      cb(fut);
      return fut.wait();
    }
  };

}).call(this);
